<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\Healingram.BuildingBlocks\Healingram.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Healingram.Contracts\Healingram.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Healingram.Modules.Matching.Tests" />
  </ItemGroup>
</Project>
